# Generated by Codex on 2026-03-31

from django.db import migrations


def backfill_missing_profiles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Profile = apps.get_model('users', 'Profile')

    missing_user_ids = User.objects.filter(profile__isnull=True).values_list('id', flat=True)
    profiles = [Profile(seller_id=user_id) for user_id in missing_user_ids]
    if profiles:
        Profile.objects.bulk_create(profiles, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.RunPython(backfill_missing_profiles, migrations.RunPython.noop),
    ]
